# Generated by Django 4.2.16 on 2024-11-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(default='описание'),
        ),
    ]
